---
# Playbook to setup folder sturctures for a new Ansible project on the localhost
# Usage: ansible-playbook new_project.yml

- name: Prompt for project path and folder name
  hosts: localhost
  vars:
    ansible_source_directory: /etc/ansible

  vars_prompt:
    - name: project_directory_path
      prompt: What is the absolute directory path to the project?
      private: no

  tasks:
    - name: Create project directory and group vars folder
      file:
        path: "{{ project_directory_path }}/group_vars"
        state: directory
      delegate_to: localhost

    - name: Copy ansible.cfg
      copy:
        src: "{{ ansible_source_directory }}/ansible.cfg"
        dest: "{{ project_directory_path }}/ansible.cfg"
      delegate_to: localhost

    - name: Copy sample Hosts file
      copy: 
        src: "{{ ansible_source_directory }}/hosts"
        dest: "{{ project_directory_path }}/hosts"
      delegate_to: localhost

    - name: Copy all.yml file
      copy: 
        src: "{{ ansible_source_directory }}/all.yml"
        dest: "{{ project_directory_path }}/group_vars/all.yml"
      delegate_to: localhost
