# File path: /etc/netplan/
network:
  version: 2
  ethernets:

    # public interface for serving DHCP traffic
    ens160:
      addresses:
        - 192.168.1.3/24
      routes:
        - to: default
          via: 192.168.1.1
      nameservers:
        addresses:
          - 1.1.1.1

    # internal interface for REST API and management traffic
    ens192:
      addresses:
        - 192.168.2.3/24
      routes:
        - to: 192.168.2.0/24
          via: 192.168.2.1
      nameservers:
        addresses:
          - 1.1.1.1
